import type { GameState } from "./types";

export function createInitialState(): GameState {
  return {
    chapter: 1,
    currentArea: "briarfold",
    currentRoom: "briarfold-main",
    region: "briarfold-valley",
    player: {
      facing: "down",
      health: 3,
      id: "aquilla",
      maxHealth: 3,
      name: "Aquilla",
      position: { x: 5, y: 5 },
      role: "shepherd-boy",
    },
    creatures: [
      {
        id: "thorn-prowler-north",
        kind: "thorn-prowler",
        name: "North Thorn Prowler",
        patrol: [
          { x: 6, y: 3 },
          { x: 6, y: 4 },
        ],
        patrolIndex: 0,
        position: { x: 6, y: 3 },
        state: "hostile",
      },
    ],
    dog: {
      command: "follow",
      id: "bracken",
      name: "Bracken",
      position: { x: 4, y: 5 },
      style: "border-collie",
    },
    flags: {},
    hazards: [
      {
        active: true,
        id: "thorn-snare-north",
        kind: "thorn-snare",
        name: "North Thorn Snare",
        position: { x: 5, y: 3 },
      },
      {
        active: true,
        id: "thorn-snare-highroad",
        kind: "thorn-snare",
        name: "Highroad Thorn Snare",
        position: { x: 13, y: 3 },
      },
    ],
    sheep: [
      { gathered: false, id: "sheep-1", name: "Lost Sheep 1", position: { x: 9, y: 4 } },
      { gathered: false, id: "sheep-2", name: "Lost Sheep 2", position: { x: 12, y: 7 } },
      { gathered: false, id: "sheep-3", name: "Lost Sheep 3", position: { x: 9, y: 10 } },
    ],
    inventory: ["shepherd-staff"],
    playtimeMinutes: 0,
    objectives: {
      creedBeaconsLit: 0,
      fearEchoCalmed: false,
      foldBellRung: false,
      foldRestored: false,
      gameComplete: false,
      gatheredSheep: 0,
      guardianCalmed: false,
      hiddenGroveFound: false,
      hiddenGroveLanternClaimed: false,
      introSeen: false,
      lanternRuinsRestored: false,
      requiredCreedBeacons: 3,
      requiredSanctumWitnessSteps: 3,
      requiredSheep: 3,
      returnedHome: false,
      sanctumWitnessSteps: 0,
      requiredThornSnares: 2,
      requiredThornProwlers: 1,
      storyComplete: false,
      thornSnaresCleared: 0,
      thornProwlersRestored: 0,
      waterRestored: false,
    },
  };
}
