export interface PixelAsset {
  rows: readonly string[];
  palette: Readonly<Record<string, string>>;
}

const overworldPalette = {
  a: "#2f5e36",
  b: "#3f7a3e",
  c: "#56994a",
  d: "#79b85c",
  e: "#a8d978",
  f: "#6b4a2b",
  g: "#9c7144",
  h: "#c79b5e",
  i: "#e6cb8e",
  j: "#46412f",
  k: "#7d745a",
  l: "#ada284",
  m: "#d8cda6",
  n: "#245e7a",
  o: "#3d8fb0",
  p: "#79cfe0",
  q: "#d8f6f2",
  r: "#b07a2b",
  s: "#e0a93a",
  t: "#f6d97a",
  u: "#fff3c4",
  v: "#5a3a22",
  w: "#7d5230",
  W: "#9c6a3c",
  x: "#241a12",
  z: "#234127",
  "1": "#f2fff0",
  "2": "#b6ecc8",
  "3": "#8fd6c0",
  "4": "#c4abe0",
  "5": "#d2553f",
  "6": "#f3ead0",
  "7": "#e8c24a",
} as const;

const characterPalette = {
  x: "#241a12",
  h: "#5a3a22",
  H: "#7d5230",
  s: "#eab98a",
  S: "#c78a5c",
  t: "#4a8a45",
  T: "#79b85c",
  d: "#2f5e36",
  g: "#e0a93a",
  G: "#f6d97a",
  p: "#c79b5e",
  P: "#9c7144",
  o: "#5a3a22",
  w: "#7d5230",
  c: "#9c6a3c",
  z: "#234127",
  n: "#e8e2d0",
} as const;

const dogPalette = {
  x: "#241a12",
  b: "#1d1810",
  w: "#e8e2d0",
  g: "#7d745a",
  t: "#c79b5e",
  z: "#234127",
} as const;

const iconPalette = {
  x: "#241a12",
  w: "#7d5230",
  W: "#9c6a3c",
  g: "#b07a2b",
  G: "#e0a93a",
  t: "#f6d97a",
  u: "#fff3c4",
  r: "#a33b2c",
  R: "#d2553f",
} as const;

const G = [
  "ccccdcccccbccccc",
  "ccbcccccddcccccc",
  "ccccccccccccdecc",
  "cccdccccccbccccc",
  "cccccecccccccccc",
  "cbcccccccdccccdc",
  "ccccdccccccccccc",
  "cccccccccbcccccc",
  "ccceccccccccdccc",
  "ccccccccccccccbc",
  "ccccdcccccbccccc",
  "ccccccccdccccccc",
  "ccbccccccccceccc",
  "ccccccdcccccdbcc",
  "cccccccccccccccc",
  "cccdccccccbcccce",
];

const g = [
  "bbbbabbcbbbbbbbb",
  "bbbcbbbbbbabbbcb",
  "bbbbbbbbcbbbbbbb",
  "bbabbbbbbbbbcbbb",
  "bbbbcbbbbabbbbbb",
  "bbbbbbbbbbbbbbbc",
  "bcbbbbabbbbbbbbb",
  "bbbbbbbbbbcbbbbb",
  "bbbbbbbcbbbbabbb",
  "bbbabcbbbbbbbbbb",
  "bbbbbbbbbbbbcbbb",
  "bbbcbbbbabbbbbbb",
  "bbbbbbbbbbbbbbbb",
  "bbbbabbbbbcbbbbb",
  "bbbbbbbbbbbbbbbc",
  "bcbbbbbbabbbbbbb",
];

const F = [
  "cccccccccccccccc",
  "ccccccc5ccccdccc",
  "cccccc575ccccccc",
  "cccccccccccc6ccc",
  "ccccccccccc676cc",
  "cdccccccccccc6cc",
  "cccccccccccccccc",
  "cccccc6ccccccccc",
  "ccccc676cccc5ccc",
  "cccccc6cccc575cc",
  "ccccccccccccc5cc",
  "cdcccccccccccccc",
  "ccccccc5cccccccc",
  "cccccc575ccccccc",
  "cccccccccccccdcc",
  "cccccccccccccccc",
];

const B = [
  "................",
  "................",
  "....xxxxxx......",
  "...xbccccbx.....",
  "..xbcddddccx....",
  "..xcdddeddcx....",
  ".xbcddeeddccbx..",
  ".xccdddddccccx..",
  ".xbcccccccccbx..",
  "..xbccccccccx...",
  "..xabbccccbax...",
  "...xaabbbax.....",
  "....xxxxxx......",
  "................",
  "................",
  "................",
];

const T = [
  "......xxxx......",
  "....xxbbbbxx....",
  "...xbccddccbx...",
  "..xbcddeedccbx..",
  "..xcddeeeeddcx..",
  ".xbcddeeeeddcbx.",
  ".xcdddeeedddccx.",
  ".xbccdddddcccbx.",
  "..xbccdddcccbx..",
  "..xabbcccbbax...",
  "...xaabbbax.....",
  ".....xvwx.......",
  ".....xvWx.......",
  ".....xvwx.......",
  "....xxvwxx......",
  "...xzzzzzzx.....",
];

const P = [
  "ggggfggggghggggg",
  "gghggggggggggfgg",
  "ggggggiggfgggggg",
  "gggfggggggggghgg",
  "ggggggghgggggggg",
  "gghggggggfgggggg",
  "ggggggggggggiggg",
  "ggggfggggghggggg",
  "ggggggggggggggfg",
  "ggghggggfggggggg",
  "ggggggggggiggggg",
  "gfgggggggggggghg",
  "ggggghgggggggggg",
  "gggggggggfgggggg",
  "ggigggggggggghgg",
  "ggggggfggggggggg",
];

const W = [
  "oooooooooooooooo",
  "onoooonooooonooo",
  "oooonoppnooooooo",
  "noooooonoooooono",
  "oooonooooonooooo",
  "ooooooonopppoono",
  "onoooooooonooooo",
  "oooooonooooonooo",
  "noooooooonoooooo",
  "ooonoooooooonooo",
  "oooooonoooonoooo",
  "onoooooooonooooo",
  "oooooppoooooonoo",
  "noooooooonoooooo",
  "oooonoooooonoooo",
  "ooooooonoooooono",
];

const w = [
  "cccccccccccccccc",
  "cbccdcccbcccdccc",
  "aaaaaaaaaaaaaaaa",
  "zzzzzzzzzzzzzzzz",
  "qqppqqppqqppqqpp",
  "oooooooooooooooo",
  "onoooonooooonooo",
  "oooonoooooonoooo",
  "noooooonoooooono",
  "oooonooooonooooo",
  "ooooooonoooooono",
  "onoooooooonooooo",
  "oooooonooooonooo",
  "noooooooonoooooo",
  "ooonoooooooonooo",
  "oooooonoooonoooo",
];

const C = [
  "jjkjjkjjkjjkjjkj",
  "jjjjjjjjjjjjjjjj",
  "xjxjjxjjxjjxjjxj",
  "jjjjjjjjjjjjjjjj",
  "jkjjkjjkjjkjjkjj",
  "jjjjjjjjjjjjjjjj",
  "jjxjjjxjjjxjjjxj",
  "jjjjjjjjjjjjjjjj",
  "kjjkjjkjjkjjkjjk",
  "jjjjjjjjjjjjjjjj",
  "xjjxjjxjjxjjxjjx",
  "jjjjjjjjjjjjjjjj",
  "jkjjkjjkjjkjjkjj",
  "jjjjjjjjjjjjjjjj",
  "jjjxjjjxjjjxjjjx",
  "jjjjjjjjjjjjjjjj",
];

const c = [
  "llllllllllllllll",
  "lmmlmlllmllmllml",
  "llllllllllllllll",
  "lllmllmlllmlllll",
  "kkkkkkkkkkkkkkkk",
  "kjkkjkkkjkkjkkkj",
  "jkkkjkkjkkkjkkjk",
  "kkjkkkjkkkjkkkkj",
  "jjkjjkjjkjkjjkjj",
  "jjjjjjjjjjjjjjjj",
  "xjxjxjjxjxjxjjxj",
  "jjjjjjjjjjjjjjjj",
  "jkjjkjjkjjkjjkjj",
  "jjjjjjjjjjjjjjjj",
  "jjkjjjkjjjkjjjkj",
  "jjjjjjjjjjjjjjjj",
];

const R = [
  "................",
  "................",
  "....llll........",
  "...lmmmml.......",
  "...lkllkl.......",
  "...lkmmll.......",
  "...llkkll.......",
  "...lkllml..ll...",
  "...llkkll.lkml..",
  "...lkmllk.lkkl..",
  "...llkllm.llkl..",
  "..jllkllljjllj..",
  ".jkkkmllkkkkkkj.",
  "jkkllkkkmlkkkllj",
  "jzzzzzzzzzzzzzzj",
  ".zzzzzzzzzzzzzz.",
];

const S = [
  "llllllllllllllll",
  "lmmmmmmmmmmmmmml",
  "lmkllllllllllkml",
  "lmkluuuuuuuulkml",
  "lmkluttttttulkml",
  "lmkluuuuuuuulkml",
  "lmkllllllllllkml",
  "lmkkkkkkkkkkkkml",
  "kkkkkkkkkkkkkkkk",
  "jjjjjjjjjjjjjjjj",
  "llllllllllllllll",
  "lkkkkkkkkkkkkkkl",
  "llllllllllllllll",
  "lkkkkkkkkkkkkkkl",
  "llllllllllllllll",
  "lkkkkkkkkkkkkkkl",
];

const A = [
  "................",
  ".......u........",
  "......utu.......",
  ".....utttu......",
  "......uuu.......",
  ".......s........",
  "......rsr.......",
  ".......s........",
  "......rsr.......",
  ".......s........",
  "......rsr.......",
  ".....rrsrr......",
  "....rr.s.rr.....",
  "...rr..s..rr....",
  "..xrrrrrrrrx....",
  "...xzzzzzzx.....",
];

const Q = [
  "kkkkkkkkkkkkkkkk",
  "kllllllllllllllk",
  "klnnnnnnnnnnnnlk",
  "klnoooooooooonlk",
  "klnopppppppponlk",
  "klnoppqqqqpponlk",
  "klnoppquuqpponlk",
  "klnoppqqqqpponlk",
  "klnopppppppponlk",
  "klnoooooooooonlk",
  "klnnnnnnnnnnnnlk",
  "kllllllllllllllk",
  "kkkkkkkkkkkkkkkk",
  "................",
  "................",
  "................",
];

const L = [
  "cccccc44cccccccc",
  "ccccc4334ccccccc",
  "cccc433134cccccc",
  "cccc431134cccccc",
  "cccc432134cccccc",
  "ccccc4334ccccccc",
  "cccccc44cccccccc",
  "cccccccccccccccc",
  "ccccccccccc44ccc",
  "cccccccccc4334cc",
  "ccccccccc433134c",
  "ccccccccc431234c",
  "ccccccccc433134c",
  "cccccccccc4334cc",
  "ccccccccccc44ccc",
  "cccccccccccccccc",
];

const aquilla = [
  "................",
  "......xxxx......",
  ".....xhhhhx.....",
  "....xhHHHHhx....",
  "....xhHHHHHx....",
  "...xhHHHHHHhx...",
  "...xsssssssx....",
  "...xsxsssxsx....",
  "...xsssssssx....",
  "...xsSsssSsx....",
  "....xssssx......",
  "....xssssx......",
  "...xtttttttx....",
  "..xtTtGGGtTtx...",
  "..xtTtGGtTTtx...",
  ".xctTtttttTtcx..",
  ".xctTtttttTtcx..",
  "..xcgPpppPgcx...",
  "...xppppPppx....",
  "...xPpx.xpPx....",
  "...xppx.xppx....",
  "...xoox.xoox....",
  "..xooox.xooox...",
  "...zzz...zzz....",
];

const sheepdog = [
  "................",
  "................",
  "....xx....xx....",
  "...xbx...xwx....",
  "..xbwwxxxwbx....",
  ".xbwwwwwwwwbx...",
  ".xwwwbwwwbwwx...",
  "..xwwwwwwwwx....",
  "...xbbbbwwx.....",
  "...xbbbwwwwx....",
  "..xbbbbwwwwx....",
  ".xbbbbxxxwwx....",
  ".xbbbxxx.xwx....",
  "..xzx....xzx....",
  "...z......z.....",
  "................",
];

const heart = [
  "................",
  "..xxx....xxx....",
  ".xRRRx..xRRRx...",
  "xRRtRRxxRRRRRx..",
  "xRtRRRRRRRRRRx..",
  "xRRRRRRRRRRRRx..",
  ".xRRRRRRRRRRx...",
  "..xRRRRRRRRx....",
  "...xRRRRRRx.....",
  "....xRRRRx......",
  ".....xRRx.......",
  "......xx........",
  "................",
  "................",
  "................",
  "................",
];

const crook = [
  "......xxx.......",
  ".....xGGGx......",
  "....xGttGx......",
  "....xGtxGx......",
  "....xGxxGx......",
  "....xGGGx.......",
  ".....xwx........",
  ".....xWx........",
  ".....xwx........",
  ".....xWx........",
  ".....xwx........",
  ".....xWx........",
  ".....xwx........",
  ".....xWx........",
  ".....xwx........",
  "....xxxxx.......",
];

export const AQUILLA_ART = {
  direction: {
    world: "Greenward",
    pixelStyle: "GBA Minish Cap-fidelity pixel art",
    tone: "hope under decay",
  },
  palette: {
    grassBase: overworldPalette.c,
    pathBase: overworldPalette.g,
    waterBase: overworldPalette.o,
    trueLight: overworldPalette.s,
    trueLightHighlight: overworldPalette.t,
    falseLight: overworldPalette["2"],
    falseLightFringe: overworldPalette["4"],
    warmOutline: overworldPalette.x,
    panel: "#231c12",
    panelTrim: "#e0a93a",
  },
  tiles: {
    G: { rows: G, palette: overworldPalette },
    g: { rows: g, palette: overworldPalette },
    F: { rows: F, palette: overworldPalette },
    B: { rows: B, palette: overworldPalette },
    T: { rows: T, palette: overworldPalette },
    P: { rows: P, palette: overworldPalette },
    W: { rows: W, palette: overworldPalette },
    w: { rows: w, palette: overworldPalette },
    C: { rows: C, palette: overworldPalette },
    c: { rows: c, palette: overworldPalette },
    R: { rows: R, palette: overworldPalette },
    S: { rows: S, palette: overworldPalette },
    A: { rows: A, palette: overworldPalette },
    Q: { rows: Q, palette: overworldPalette },
    L: { rows: L, palette: overworldPalette },
  } satisfies Record<string, PixelAsset>,
  sprites: {
    aquilla: { rows: aquilla, palette: characterPalette },
    sheepdog: { rows: sheepdog, palette: dogPalette },
  } satisfies Record<string, PixelAsset>,
  icons: {
    heart: { rows: heart, palette: iconPalette },
    crook: { rows: crook, palette: iconPalette },
  } satisfies Record<string, PixelAsset>,
  sceneMap: [
    "TTGGGGGGGGGGGGGGGGTT",
    "TGGGFGGGBGGGFGGGGGGT",
    "GGGGGGGGGGGGGGSAGGGG",
    "GGBGGPPPGGGGGGSGGGGB",
    "GGGGGPGPGGGGGGSGGGGG",
    "GGFGGPGPGGGRGGGGGFGG",
    "GGGGGPGPPPPPPPPPGGGG",
    "GGGGGPGGGGGGGGPGGLGG",
    "ccccccccGGGGGGPGGGGG",
    "CCCCCCCcGGFGGGPGGGGB",
    "WWWWWWWwGGGGGGPGGGGG",
    "WWWWWWWwGGGGBGGGGFGG",
    "WWWWWWWQGGGGGGGGGGGG",
  ],
  oldPastureSceneMap: [
    "TTGGGGGGGGGGGGGGGGTT",
    "TGGGFGGGGGGGGGFGGGGT",
    "GGGGGGPPPPPPGGGGGGBG",
    "GGBGGGPGGGGPGGGGFGGG",
    "GGGGGGPGLLGPGGGGGGGG",
    "GGFGGGPGGGGPGGGGBGGG",
    "GGPPPPPPGGGPPPPPPPGG",
    "GGPGGGGGGGGGGGGGGPGG",
    "GGPGGGBGGFFGGGBGGPGG",
    "GGPPPPPPPPPPPPPPPPGG",
    "GGGGGGGGwWWWWwGGGGGG",
    "GGGFGGGGwWWWWwGGGFGG",
    "TTGGGGGGQGGGGGGGGGTT",
  ],
  lanternRuinsSceneMap: [
    "TTGGGGGGGGGGGGGGGGTT",
    "TGGGFGGGGGGGGFGGGGGT",
    "GGGGGGGGGGGGGGGGGGGG",
    "GGGBGGGLLLGGGLLLGGGG",
    "GGGGGGGGGGGGGGGGGGGG",
    "GGFGGAGGGGAGGGGAGGGG",
    "GGPPPPPPPPPPPPPPPPGG",
    "GGPGGGGGGGGGGGGGGPGG",
    "GGPGGGBGGFFGGGBGGPGG",
    "GGPPPPPPPPPPPPPPPPGG",
    "GGGGGGGGwWWWWwGGGGGG",
    "GGGFGGGGwWWWWwGGGFGG",
    "TTGGGGGGQGGGGGGGGGTT",
  ],
} as const;
